### ISSUE TITLE
Check audit result in CI

### ISSUE THREAD

**Issue by smooth97** [smooth97/next-boilerplate#18]
목적 : 연관 라이브러리의 보안이슈는 프로젝트의 잠재적 위협이 됨

GitHub action에서 `npm audit` 을 실행하여,
 1. hard나 critical 반경시 빌드 실패
 2. medium이 있을 경우에는 warning
 3. low만 있을 경우 CI통과
 4. npm audit의 결과를 GitHub action 에 코멘트로 등록(기능 존재시)

**Comment by Kuniz** [comment]
Audit Result에서 critical/hard/medium/low 의 의미가 어떻게 되는지 한 번 찾아봐바. 그래야 업데이트 시급성을 이해할 수 있을 것 같음. 기존에 예시 한 두 개도 같이 보면 더 좋을거야 ~ 👍  @smooth97
